/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Database.Database;
import MarkovChains.MarkovLogic;
import Properties.Properties;
import Properties.PropertiesGUI;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author drapek
 */
public class MainGUI extends javax.swing.JFrame {
    
    
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jChatPanel = new javax.swing.JPanel();
        jReplyField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jChatArea = new javax.swing.JTextArea();
        jSendButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jChartsPanel = new javax.swing.JPanel();
        jMarkovDiagramPanel = new javax.swing.JPanel();
        jChangeDbButton = new javax.swing.JButton();
        jTxtIloscSlowWBazie = new javax.swing.JLabel();
        jTxtNmbWordsInDb = new javax.swing.JLabel();
        jTxtPrawdopodobTegoZdania = new javax.swing.JLabel();
        jTxtProbability = new javax.swing.JLabel();
        jSaveDBButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jChatPanel.setBackground(new java.awt.Color(30, 168, 221));

        jReplyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReplyFieldActionPerformed(evt);
            }
        });

        jChatArea.setColumns(20);
        jChatArea.setRows(5);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jChatArea, org.jdesktop.beansbinding.ELProperty.create("false"), jChatArea, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(jChatArea);

        jSendButton.setText("Wyślij");
        jSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jChatPanelLayout = new javax.swing.GroupLayout(jChatPanel);
        jChatPanel.setLayout(jChatPanelLayout);
        jChatPanelLayout.setHorizontalGroup(
            jChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jChatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jChatPanelLayout.createSequentialGroup()
                        .addComponent(jReplyField, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jChatPanelLayout.setVerticalGroup(
            jChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jChatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jReplyField)
                    .addComponent(jSendButton, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(254, 227, 144));

        jLabel1.setText("Umysł Noobot'a");

        javax.swing.GroupLayout jChartsPanelLayout = new javax.swing.GroupLayout(jChartsPanel);
        jChartsPanel.setLayout(jChartsPanelLayout);
        jChartsPanelLayout.setHorizontalGroup(
            jChartsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jChartsPanelLayout.setVerticalGroup(
            jChartsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jMarkovDiagramPanelLayout = new javax.swing.GroupLayout(jMarkovDiagramPanel);
        jMarkovDiagramPanel.setLayout(jMarkovDiagramPanelLayout);
        jMarkovDiagramPanelLayout.setHorizontalGroup(
            jMarkovDiagramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jMarkovDiagramPanelLayout.setVerticalGroup(
            jMarkovDiagramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );

        jChangeDbButton.setText("Ustawienia");
        jChangeDbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChangeDbButtonActionPerformed(evt);
            }
        });

        jTxtIloscSlowWBazie.setText("Ilość słów w bazie:");

        jTxtNmbWordsInDb.setText("0");

        jTxtPrawdopodobTegoZdania.setText("Prawdopodobieństwo tego zdania:");

        jTxtProbability.setText("0,00");

        jSaveDBButton.setText("Zapisz bazę danych");
        jSaveDBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveDBButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTxtPrawdopodobTegoZdania)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtNmbWordsInDb)
                                    .addComponent(jTxtProbability))))
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMarkovDiagramPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jChartsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxtIloscSlowWBazie)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jChangeDbButton)
                                .addGap(18, 18, 18)
                                .addComponent(jSaveDBButton)
                                .addGap(34, 34, 34)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChartsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jMarkovDiagramPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPrawdopodobTegoZdania)
                    .addComponent(jTxtProbability))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtIloscSlowWBazie)
                    .addComponent(jTxtNmbWordsInDb))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChangeDbButton)
                    .addComponent(jSaveDBButton))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jChatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jChatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jReplyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReplyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jReplyFieldActionPerformed

    private void jSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSendButtonActionPerformed
        // TODO add your handling code here:
        addSentenceToChat("Ty", jReplyField.getText());
        
        
        //wyślij do dodania do bazy
        mainDB.addSentenceToDb(jReplyField.getText(), "UserInput: " + (new Date()).toString());
        
        //wygeneruj odpowiedź
        addSentenceToChat("Noobot", generator.generateSentence(jReplyField.getText()));
        
        //wyczyść okienko inputu user'a
        jReplyField.setText("");
        
        //uzupełnij statystyki danymi
        jTxtProbability.setText( (new Double(MarkovChains.MarkovLogic.statystyki.getActualProbabilityOfSentence() )).toString() );
        jTxtNmbWordsInDb.setText( (new Integer(MarkovChains.MarkovLogic.statystyki.getNumberOfWordsInDb()).toString()));
        
        //ustaw przed nową generacją tekstu prawdopodobienstwo na 1
        MarkovChains.MarkovLogic.statystyki.resetActualProbabilityOfSentence();
        
        
        
    }//GEN-LAST:event_jSendButtonActionPerformed

    private void jSaveDBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveDBButtonActionPerformed
        
            mainDB.writeDbAsCSV(mainDB.getDbPath());        // TODO add your handling code here:
       
    }//GEN-LAST:event_jSaveDBButtonActionPerformed

    private void jChangeDbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChangeDbButtonActionPerformed
        PropertiesGUI noweOkno = new PropertiesGUI(); 
        noweOkno.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        noweOkno.setVisible(true);
    }//GEN-LAST:event_jChangeDbButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
        
        //moje
           mainDB = new Database();
           mainProperties = new Properties();
           generator = new MarkovLogic(mainDB, mainProperties);
           
           
       
    }
    
    public void addSentenceToChat(String who, String Sentence) {
        jChatArea.append(who + ": " + Sentence + "\n");

        
    }
    
       
    
    static Database mainDB;
    public static Properties mainProperties;
    static MarkovLogic generator;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jChangeDbButton;
    private javax.swing.JPanel jChartsPanel;
    private javax.swing.JTextArea jChatArea;
    private javax.swing.JPanel jChatPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jMarkovDiagramPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jReplyField;
    private javax.swing.JButton jSaveDBButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSendButton;
    private javax.swing.JLabel jTxtIloscSlowWBazie;
    private javax.swing.JLabel jTxtNmbWordsInDb;
    private javax.swing.JLabel jTxtPrawdopodobTegoZdania;
    private javax.swing.JLabel jTxtProbability;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}

